# Azure Deployment Environment カタログ定義
name: "ACI Development Environment"
version: "1.0.0"
description: "Azure Container Instances を使用した開発環境のカタログ"

templates:
  - name: "aci-simple"
    path: "./templates/aci-simple"
    description: "シンプルな Azure Container Instances デプロイメント"
    supportedRegions:
      - "japaneast"
      - "japanwest"
      - "eastus"
      - "westus2"
      - "westeurope"